---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kufefe.rbac.roleName" . }}
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      {{ include "kufefe.rbac.matchLabel" . }}
