apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: requests.kufefe.io
spec:
  group: kufefe.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                role:
                  type: string
                  description: "The role to be assigned to the user"
            status:
              type: object
              properties:
                generatedName:
                  type: string
                  description: "The generated name for the user"
                  x-kubernetes-validations:
                    - message: Value is immutable
                      rule: self == oldSelf
                kubeconfig:
                  type: string
                  description: "The kubeconfig for the user"
                ready:
                  type: boolean
                  description: "True if the request has been fulfilled"
                  default: false
                expiresAt:
                  type: integer
                  description: "Timestamp when the request expires"
                  x-kubernetes-validations:
                    - message: Value is immutable
                      rule: self == oldSelf
      subresources:
        status: {}
      additionalPrinterColumns:
        - jsonPath: .status.ready
          name: READY
          type: boolean
        - jsonPath: .metadata.creationTimestamp
          name: AGE
          type: date
  scope: Cluster
  names:
    plural: requests
    singular: request
    kind: Request
    shortNames:
    - rq
    - req
