---
kufefe:
  expireMinutes: 60
  clusterUrl: "" # If left empty, Kufefe will try to auto-detect. If auto-detection fails, you must specify this.
  # clusterName: "" # Set this if you have multiple clusters and want to distinguish them during auto-detection.

image:
  repository: quay.io/duk4s/kufefe
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  annotations: {}
  name: "kufefe-sa"

podAnnotations: {}

podSecurityContext: {}

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

resources: {}
  # limits:
  #   cpu: 50m
  #   memory: 64Mi
  # requests:
  #   cpu: 25m
  #   memory: 32Mi

nodeSelector: {}

tolerations: []

affinity: {}
